/*
 * Whispir Platform API
 * Whispir Platform API for cross channel and multi channel communications. Documentation on each endpoint is available at https://developers.whispir.com.
 *
 * The version of the OpenAPI document: 1.1.3
 * Contact: support@whispir.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.whispir.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.whispir.client.JSON;

/**
 * The details about this particular message sender/responder
 */
@ApiModel(description = "The details about this particular message sender/responder")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-12-06T03:10:46.360132Z[Etc/UTC]")
public class CallbackCallFrom {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_MRI = "mri";
  @SerializedName(SERIALIZED_NAME_MRI)
  private String mri;

  public static final String SERIALIZED_NAME_MOBILE = "mobile";
  @SerializedName(SERIALIZED_NAME_MOBILE)
  private String mobile;

  public static final String SERIALIZED_NAME_VOICE = "voice";
  @SerializedName(SERIALIZED_NAME_VOICE)
  private String voice;

  public static final String SERIALIZED_NAME_EMAIL = "email";
  @SerializedName(SERIALIZED_NAME_EMAIL)
  private String email;

  public CallbackCallFrom() { 
  }

  
  public CallbackCallFrom(
     String name, 
     String mri, 
     String mobile, 
     String voice, 
     String email
  ) {
    this();
    this.name = name;
    this.mri = mri;
    this.mobile = mobile;
    this.voice = voice;
    this.email = email;
  }

   /**
   * The name of the sender of this message
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "John Wick", value = "The name of the sender of this message")

  public String getName() {
    return name;
  }




   /**
   * The unique identifier for this contact within Whispir
   * @return mri
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "support@whispir.com", value = "The unique identifier for this contact within Whispir")

  public String getMri() {
    return mri;
  }




   /**
   * The mobile phone number associated with this sender
   * @return mobile
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "61400400400", value = "The mobile phone number associated with this sender")

  public String getMobile() {
    return mobile;
  }




   /**
   * The phone number associated with the voice channel for this sender
   * @return voice
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "61400400400", value = "The phone number associated with the voice channel for this sender")

  public String getVoice() {
    return voice;
  }




   /**
   * The email address associated with the email channel for this sender
   * @return email
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "support@whispir.com", value = "The email address associated with the email channel for this sender")

  public String getEmail() {
    return email;
  }





  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CallbackCallFrom callbackCallFrom = (CallbackCallFrom) o;
    return Objects.equals(this.name, callbackCallFrom.name) &&
        Objects.equals(this.mri, callbackCallFrom.mri) &&
        Objects.equals(this.mobile, callbackCallFrom.mobile) &&
        Objects.equals(this.voice, callbackCallFrom.voice) &&
        Objects.equals(this.email, callbackCallFrom.email);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, mri, mobile, voice, email);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CallbackCallFrom {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    mri: ").append(toIndentedString(mri)).append("\n");
    sb.append("    mobile: ").append(toIndentedString(mobile)).append("\n");
    sb.append("    voice: ").append(toIndentedString(voice)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("name");
    openapiFields.add("mri");
    openapiFields.add("mobile");
    openapiFields.add("voice");
    openapiFields.add("email");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to CallbackCallFrom
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (CallbackCallFrom.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in CallbackCallFrom is not found in the empty JSON string", CallbackCallFrom.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!CallbackCallFrom.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CallbackCallFrom` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if (jsonObj.get("name") != null && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if (jsonObj.get("mri") != null && !jsonObj.get("mri").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `mri` to be a primitive type in the JSON string but got `%s`", jsonObj.get("mri").toString()));
      }
      if (jsonObj.get("mobile") != null && !jsonObj.get("mobile").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `mobile` to be a primitive type in the JSON string but got `%s`", jsonObj.get("mobile").toString()));
      }
      if (jsonObj.get("voice") != null && !jsonObj.get("voice").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `voice` to be a primitive type in the JSON string but got `%s`", jsonObj.get("voice").toString()));
      }
      if (jsonObj.get("email") != null && !jsonObj.get("email").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `email` to be a primitive type in the JSON string but got `%s`", jsonObj.get("email").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CallbackCallFrom.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CallbackCallFrom' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CallbackCallFrom> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CallbackCallFrom.class));

       return (TypeAdapter<T>) new TypeAdapter<CallbackCallFrom>() {
           @Override
           public void write(JsonWriter out, CallbackCallFrom value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CallbackCallFrom read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of CallbackCallFrom given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of CallbackCallFrom
  * @throws IOException if the JSON string is invalid with respect to CallbackCallFrom
  */
  public static CallbackCallFrom fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CallbackCallFrom.class);
  }

 /**
  * Convert an instance of CallbackCallFrom to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

