/*
 * Whispir Platform API
 * Whispir Platform API for cross channel and multi channel communications. Documentation on each endpoint is available at https://developers.whispir.com.
 *
 * The version of the OpenAPI document: 1.1.3
 * Contact: support@whispir.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.whispir.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.whispir.client.JSON;

/**
 * The object defining options for message sender aliasing.
 */
@ApiModel(description = "The object defining options for message sender aliasing.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-12-06T03:10:46.360132Z[Etc/UTC]")
public class MessageFeaturesAliasOption {
  public static final String SERIALIZED_NAME_ALIAS_NAME = "aliasName";
  @SerializedName(SERIALIZED_NAME_ALIAS_NAME)
  private String aliasName;

  public MessageFeaturesAliasOption() { 
  }

  public MessageFeaturesAliasOption aliasName(String aliasName) {
    
    this.aliasName = aliasName;
    return this;
  }

   /**
   * The name of the alias configured to modify the message sender.
   * @return aliasName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Marketing", value = "The name of the alias configured to modify the message sender.")

  public String getAliasName() {
    return aliasName;
  }


  public void setAliasName(String aliasName) {
    this.aliasName = aliasName;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MessageFeaturesAliasOption messageFeaturesAliasOption = (MessageFeaturesAliasOption) o;
    return Objects.equals(this.aliasName, messageFeaturesAliasOption.aliasName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(aliasName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MessageFeaturesAliasOption {\n");
    sb.append("    aliasName: ").append(toIndentedString(aliasName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("aliasName");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to MessageFeaturesAliasOption
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (MessageFeaturesAliasOption.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in MessageFeaturesAliasOption is not found in the empty JSON string", MessageFeaturesAliasOption.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!MessageFeaturesAliasOption.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `MessageFeaturesAliasOption` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if (jsonObj.get("aliasName") != null && !jsonObj.get("aliasName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `aliasName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("aliasName").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!MessageFeaturesAliasOption.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'MessageFeaturesAliasOption' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<MessageFeaturesAliasOption> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(MessageFeaturesAliasOption.class));

       return (TypeAdapter<T>) new TypeAdapter<MessageFeaturesAliasOption>() {
           @Override
           public void write(JsonWriter out, MessageFeaturesAliasOption value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public MessageFeaturesAliasOption read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of MessageFeaturesAliasOption given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of MessageFeaturesAliasOption
  * @throws IOException if the JSON string is invalid with respect to MessageFeaturesAliasOption
  */
  public static MessageFeaturesAliasOption fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, MessageFeaturesAliasOption.class);
  }

 /**
  * Convert an instance of MessageFeaturesAliasOption to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

