/*
 * Whispir Platform API
 * Whispir Platform API for cross channel and multi channel communications. Documentation on each endpoint is available at https://developers.whispir.com.
 *
 * The version of the OpenAPI document: 1.1.3
 * Contact: support@whispir.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.whispir.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for MessageFeaturesPushOptionsFCM
 */
public class MessageFeaturesPushOptionsFCMTest {
    private final MessageFeaturesPushOptionsFCM model = new MessageFeaturesPushOptionsFCM();

    /**
     * Model tests for MessageFeaturesPushOptionsFCM
     */
    @Test
    public void testMessageFeaturesPushOptionsFCM() {
        // TODO: test MessageFeaturesPushOptionsFCM
    }

    /**
     * Test the property 'androidChannelId'
     */
    @Test
    public void androidChannelIdTest() {
        // TODO: test androidChannelId
    }

    /**
     * Test the property 'sound'
     */
    @Test
    public void soundTest() {
        // TODO: test sound
    }

    /**
     * Test the property 'action'
     */
    @Test
    public void actionTest() {
        // TODO: test action
    }

    /**
     * Test the property 'image'
     */
    @Test
    public void imageTest() {
        // TODO: test image
    }

}
