/*
 * Whispir Platform API
 * Whispir Platform API for cross channel and multi channel communications. Documentation on each endpoint is available at https://developers.whispir.com.
 *
 * The version of the OpenAPI document: 1.1.3
 * Contact: support@whispir.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.whispir.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for MessageResponseDetailedStatusResponseMessage
 */
public class MessageResponseDetailedStatusResponseMessageTest {
    private final MessageResponseDetailedStatusResponseMessage model = new MessageResponseDetailedStatusResponseMessage();

    /**
     * Model tests for MessageResponseDetailedStatusResponseMessage
     */
    @Test
    public void testMessageResponseDetailedStatusResponseMessage() {
        // TODO: test MessageResponseDetailedStatusResponseMessage
    }

    /**
     * Test the property 'content'
     */
    @Test
    public void contentTest() {
        // TODO: test content
    }

    /**
     * Test the property 'acknowledged'
     */
    @Test
    public void acknowledgedTest() {
        // TODO: test acknowledged
    }

    /**
     * Test the property 'channel'
     */
    @Test
    public void channelTest() {
        // TODO: test channel
    }

}
