/*
 * Whispir Platform API
 * Whispir Platform API for cross channel and multi channel communications. Documentation on each endpoint is available at https://developers.whispir.com.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@whispir.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.LinkInner;
import org.openapitools.client.model.LocationsInner;
import org.openapitools.client.model.MessagingoptionsInner;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Contact
 */
public class ContactTest {
    private final Contact model = new Contact();

    /**
     * Model tests for Contact
     */
    @Test
    public void testContact() {
        // TODO: test Contact
    }

    /**
     * Test the property 'firstName'
     */
    @Test
    public void firstNameTest() {
        // TODO: test firstName
    }

    /**
     * Test the property 'lastName'
     */
    @Test
    public void lastNameTest() {
        // TODO: test lastName
    }

    /**
     * Test the property 'workMobilePhone1'
     */
    @Test
    public void workMobilePhone1Test() {
        // TODO: test workMobilePhone1
    }

    /**
     * Test the property 'workEmailAddress1'
     */
    @Test
    public void workEmailAddress1Test() {
        // TODO: test workEmailAddress1
    }

    /**
     * Test the property 'workCountry'
     */
    @Test
    public void workCountryTest() {
        // TODO: test workCountry
    }

    /**
     * Test the property 'timezone'
     */
    @Test
    public void timezoneTest() {
        // TODO: test timezone
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'workMobilePhone2'
     */
    @Test
    public void workMobilePhone2Test() {
        // TODO: test workMobilePhone2
    }

    /**
     * Test the property 'workEmailAddress2'
     */
    @Test
    public void workEmailAddress2Test() {
        // TODO: test workEmailAddress2
    }

    /**
     * Test the property 'workPhoneAreaCode1'
     */
    @Test
    public void workPhoneAreaCode1Test() {
        // TODO: test workPhoneAreaCode1
    }

    /**
     * Test the property 'workPhone1'
     */
    @Test
    public void workPhone1Test() {
        // TODO: test workPhone1
    }

    /**
     * Test the property 'workPhoneAreaCode2'
     */
    @Test
    public void workPhoneAreaCode2Test() {
        // TODO: test workPhoneAreaCode2
    }

    /**
     * Test the property 'workPhone2'
     */
    @Test
    public void workPhone2Test() {
        // TODO: test workPhone2
    }

    /**
     * Test the property 'workFaxAreaCode1'
     */
    @Test
    public void workFaxAreaCode1Test() {
        // TODO: test workFaxAreaCode1
    }

    /**
     * Test the property 'workFax1'
     */
    @Test
    public void workFax1Test() {
        // TODO: test workFax1
    }

    /**
     * Test the property 'workSatellitePhone'
     */
    @Test
    public void workSatellitePhoneTest() {
        // TODO: test workSatellitePhone
    }

    /**
     * Test the property 'workOtherPhone'
     */
    @Test
    public void workOtherPhoneTest() {
        // TODO: test workOtherPhone
    }

    /**
     * Test the property 'workAddress1'
     */
    @Test
    public void workAddress1Test() {
        // TODO: test workAddress1
    }

    /**
     * Test the property 'workAddress2'
     */
    @Test
    public void workAddress2Test() {
        // TODO: test workAddress2
    }

    /**
     * Test the property 'workSuburb'
     */
    @Test
    public void workSuburbTest() {
        // TODO: test workSuburb
    }

    /**
     * Test the property 'workState'
     */
    @Test
    public void workStateTest() {
        // TODO: test workState
    }

    /**
     * Test the property 'workPostCode'
     */
    @Test
    public void workPostCodeTest() {
        // TODO: test workPostCode
    }

    /**
     * Test the property 'workPostalAddress1'
     */
    @Test
    public void workPostalAddress1Test() {
        // TODO: test workPostalAddress1
    }

    /**
     * Test the property 'workPostalAddress2'
     */
    @Test
    public void workPostalAddress2Test() {
        // TODO: test workPostalAddress2
    }

    /**
     * Test the property 'workPostalSuburb'
     */
    @Test
    public void workPostalSuburbTest() {
        // TODO: test workPostalSuburb
    }

    /**
     * Test the property 'workPostalState'
     */
    @Test
    public void workPostalStateTest() {
        // TODO: test workPostalState
    }

    /**
     * Test the property 'workPostalPostCode'
     */
    @Test
    public void workPostalPostCodeTest() {
        // TODO: test workPostalPostCode
    }

    /**
     * Test the property 'personalEmailAddress1'
     */
    @Test
    public void personalEmailAddress1Test() {
        // TODO: test personalEmailAddress1
    }

    /**
     * Test the property 'personalEmailAddress2'
     */
    @Test
    public void personalEmailAddress2Test() {
        // TODO: test personalEmailAddress2
    }

    /**
     * Test the property 'personalAddress1'
     */
    @Test
    public void personalAddress1Test() {
        // TODO: test personalAddress1
    }

    /**
     * Test the property 'personalAddress2'
     */
    @Test
    public void personalAddress2Test() {
        // TODO: test personalAddress2
    }

    /**
     * Test the property 'personalSuburb'
     */
    @Test
    public void personalSuburbTest() {
        // TODO: test personalSuburb
    }

    /**
     * Test the property 'personalState'
     */
    @Test
    public void personalStateTest() {
        // TODO: test personalState
    }

    /**
     * Test the property 'personalPostCode'
     */
    @Test
    public void personalPostCodeTest() {
        // TODO: test personalPostCode
    }

    /**
     * Test the property 'personalCountry'
     */
    @Test
    public void personalCountryTest() {
        // TODO: test personalCountry
    }

    /**
     * Test the property 'personalPhoneAreaCode1'
     */
    @Test
    public void personalPhoneAreaCode1Test() {
        // TODO: test personalPhoneAreaCode1
    }

    /**
     * Test the property 'personalPhone1'
     */
    @Test
    public void personalPhone1Test() {
        // TODO: test personalPhone1
    }

    /**
     * Test the property 'personalPhoneAreaCode2'
     */
    @Test
    public void personalPhoneAreaCode2Test() {
        // TODO: test personalPhoneAreaCode2
    }

    /**
     * Test the property 'personalPhone2'
     */
    @Test
    public void personalPhone2Test() {
        // TODO: test personalPhone2
    }

    /**
     * Test the property 'personalFaxAreaCode1'
     */
    @Test
    public void personalFaxAreaCode1Test() {
        // TODO: test personalFaxAreaCode1
    }

    /**
     * Test the property 'personalFax1'
     */
    @Test
    public void personalFax1Test() {
        // TODO: test personalFax1
    }

    /**
     * Test the property 'otherPhoneAreaCode1'
     */
    @Test
    public void otherPhoneAreaCode1Test() {
        // TODO: test otherPhoneAreaCode1
    }

    /**
     * Test the property 'otherPhone1'
     */
    @Test
    public void otherPhone1Test() {
        // TODO: test otherPhone1
    }

    /**
     * Test the property 'otherMobile'
     */
    @Test
    public void otherMobileTest() {
        // TODO: test otherMobile
    }

    /**
     * Test the property 'otherFirstName'
     */
    @Test
    public void otherFirstNameTest() {
        // TODO: test otherFirstName
    }

    /**
     * Test the property 'otherLastName'
     */
    @Test
    public void otherLastNameTest() {
        // TODO: test otherLastName
    }

    /**
     * Test the property 'otherTitle'
     */
    @Test
    public void otherTitleTest() {
        // TODO: test otherTitle
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'companyName'
     */
    @Test
    public void companyNameTest() {
        // TODO: test companyName
    }

    /**
     * Test the property 'jobTitle'
     */
    @Test
    public void jobTitleTest() {
        // TODO: test jobTitle
    }

    /**
     * Test the property 'division'
     */
    @Test
    public void divisionTest() {
        // TODO: test division
    }

    /**
     * Test the property 'businessUnit'
     */
    @Test
    public void businessUnitTest() {
        // TODO: test businessUnit
    }

    /**
     * Test the property 'department'
     */
    @Test
    public void departmentTest() {
        // TODO: test department
    }

    /**
     * Test the property 'teamName1'
     */
    @Test
    public void teamName1Test() {
        // TODO: test teamName1
    }

    /**
     * Test the property 'teamName2'
     */
    @Test
    public void teamName2Test() {
        // TODO: test teamName2
    }

    /**
     * Test the property 'role1'
     */
    @Test
    public void role1Test() {
        // TODO: test role1
    }

    /**
     * Test the property 'role2'
     */
    @Test
    public void role2Test() {
        // TODO: test role2
    }

    /**
     * Test the property 'locations'
     */
    @Test
    public void locationsTest() {
        // TODO: test locations
    }

    /**
     * Test the property 'messagingoptions'
     */
    @Test
    public void messagingoptionsTest() {
        // TODO: test messagingoptions
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'mri'
     */
    @Test
    public void mriTest() {
        // TODO: test mri
    }

    /**
     * Test the property 'devices'
     */
    @Test
    public void devicesTest() {
        // TODO: test devices
    }

    /**
     * Test the property 'link'
     */
    @Test
    public void linkTest() {
        // TODO: test link
    }

    /**
     * Test the property 'lastModifiedTime'
     */
    @Test
    public void lastModifiedTimeTest() {
        // TODO: test lastModifiedTime
    }

}
