/*
 * Whispir Platform API
 * Whispir Platform API for cross channel and multi channel communications. Documentation on each endpoint is available at https://developers.whispir.com.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@whispir.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.FeaturesAliasOption;
import org.openapitools.client.model.FeaturesPushOptions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Features
 */
public class FeaturesTest {
    private final Features model = new Features();

    /**
     * Model tests for Features
     */
    @Test
    public void testFeatures() {
        // TODO: test Features
    }

    /**
     * Test the property 'pushOptions'
     */
    @Test
    public void pushOptionsTest() {
        // TODO: test pushOptions
    }

    /**
     * Test the property 'aliasOption'
     */
    @Test
    public void aliasOptionTest() {
        // TODO: test aliasOption
    }

}
