/*
 * Whispir Platform API
 * Whispir Platform API for cross channel and multi channel communications. Documentation on each endpoint is available at https://developers.whispir.com.
 *
 * The version of the OpenAPI document: 1.1.1
 * Contact: support@whispir.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.ResponseRule;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import whispir_sdk_java.JSON;

/**
 * GetResponseRules200Response
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-11-22T09:15:03.121580Z[Etc/UTC]")
public class GetResponseRules200Response {
  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private String status;

  public static final String SERIALIZED_NAME_RESPONSE_RULES = "responseRules";
  @SerializedName(SERIALIZED_NAME_RESPONSE_RULES)
  private List<ResponseRule> responseRules = new ArrayList<>();

  public GetResponseRules200Response() { 
  }

  
  public GetResponseRules200Response(
     String status, 
     List<ResponseRule> responseRules
  ) {
    this();
    this.status = status;
    this.responseRules = responseRules;
  }

   /**
   * Provides the total number of records fetched. This attribute may return \&quot;No records found\&quot; when there are no response rules available.
   * @return status
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "1 to 8 of 8", required = true, value = "Provides the total number of records fetched. This attribute may return \"No records found\" when there are no response rules available.")

  public String getStatus() {
    return status;
  }




   /**
   * The list of response rules
   * @return responseRules
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The list of response rules")

  public List<ResponseRule> getResponseRules() {
    return responseRules;
  }





  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetResponseRules200Response getResponseRules200Response = (GetResponseRules200Response) o;
    return Objects.equals(this.status, getResponseRules200Response.status) &&
        Objects.equals(this.responseRules, getResponseRules200Response.responseRules);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, responseRules);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetResponseRules200Response {\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    responseRules: ").append(toIndentedString(responseRules)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("status");
    openapiFields.add("responseRules");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("status");
    openapiRequiredFields.add("responseRules");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to GetResponseRules200Response
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (GetResponseRules200Response.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in GetResponseRules200Response is not found in the empty JSON string", GetResponseRules200Response.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!GetResponseRules200Response.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `GetResponseRules200Response` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : GetResponseRules200Response.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (jsonObj.get("status") != null && !jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
      JsonArray jsonArrayresponseRules = jsonObj.getAsJsonArray("responseRules");
      if (jsonArrayresponseRules != null) {
        // ensure the json data is an array
        if (!jsonObj.get("responseRules").isJsonArray()) {
          throw new IllegalArgumentException(String.format("Expected the field `responseRules` to be an array in the JSON string but got `%s`", jsonObj.get("responseRules").toString()));
        }

        // validate the optional field `responseRules` (array)
        for (int i = 0; i < jsonArrayresponseRules.size(); i++) {
          ResponseRule.validateJsonObject(jsonArrayresponseRules.get(i).getAsJsonObject());
        };
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetResponseRules200Response.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetResponseRules200Response' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetResponseRules200Response> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetResponseRules200Response.class));

       return (TypeAdapter<T>) new TypeAdapter<GetResponseRules200Response>() {
           @Override
           public void write(JsonWriter out, GetResponseRules200Response value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GetResponseRules200Response read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of GetResponseRules200Response given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of GetResponseRules200Response
  * @throws IOException if the JSON string is invalid with respect to GetResponseRules200Response
  */
  public static GetResponseRules200Response fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetResponseRules200Response.class);
  }

 /**
  * Convert an instance of GetResponseRules200Response to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

