/*
 * Whispir Platform API
 * Whispir Platform API for cross channel and multi channel communications. Documentation on each endpoint is available at https://developers.whispir.com.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: support@whispir.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.LinkInner;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import whispir_sdk_java.JSON;

/**
 * GetTemplates200ResponseMessagetemplatesInner
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-11-21T01:55:16.197234Z[Etc/UTC]")
public class GetTemplates200ResponseMessagetemplatesInner {
  public static final String SERIALIZED_NAME_MESSAGE_TEMPLATE_NAME = "messageTemplateName";
  @SerializedName(SERIALIZED_NAME_MESSAGE_TEMPLATE_NAME)
  private String messageTemplateName;

  public static final String SERIALIZED_NAME_MESSAGE_TEMPLATE_DESCRIPTION = "messageTemplateDescription";
  @SerializedName(SERIALIZED_NAME_MESSAGE_TEMPLATE_DESCRIPTION)
  private String messageTemplateDescription;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_LINK = "link";
  @SerializedName(SERIALIZED_NAME_LINK)
  private List<LinkInner> link = null;

  public GetTemplates200ResponseMessagetemplatesInner() { 
  }

  
  public GetTemplates200ResponseMessagetemplatesInner(
     String messageTemplateName, 
     String messageTemplateDescription, 
     String id, 
     List<LinkInner> link
  ) {
    this();
    this.messageTemplateName = messageTemplateName;
    this.messageTemplateDescription = messageTemplateDescription;
    this.id = id;
    this.link = link;
  }

   /**
   * Specifies the name of the message template
   * @return messageTemplateName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "Test Template", value = "Specifies the name of the message template")

  public String getMessageTemplateName() {
    return messageTemplateName;
  }




   /**
   * Specifies the description of the message template, so that anyone can understand its purpose
   * @return messageTemplateDescription
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "The test messate template.", value = "Specifies the description of the message template, so that anyone can understand its purpose")

  public String getMessageTemplateDescription() {
    return messageTemplateDescription;
  }




   /**
   * Specifies the template id needed for all the API Operations
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "236EA3E3E63439DA", value = "Specifies the template id needed for all the API Operations")

  public String getId() {
    return id;
  }




   /**
   * A [HATEOAS](https://en.wikipedia.org/wiki/HATEOAS) link object, describing all discoverable resources in relation to the original request.
   * @return link
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A [HATEOAS](https://en.wikipedia.org/wiki/HATEOAS) link object, describing all discoverable resources in relation to the original request.")

  public List<LinkInner> getLink() {
    return link;
  }





  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetTemplates200ResponseMessagetemplatesInner getTemplates200ResponseMessagetemplatesInner = (GetTemplates200ResponseMessagetemplatesInner) o;
    return Objects.equals(this.messageTemplateName, getTemplates200ResponseMessagetemplatesInner.messageTemplateName) &&
        Objects.equals(this.messageTemplateDescription, getTemplates200ResponseMessagetemplatesInner.messageTemplateDescription) &&
        Objects.equals(this.id, getTemplates200ResponseMessagetemplatesInner.id) &&
        Objects.equals(this.link, getTemplates200ResponseMessagetemplatesInner.link);
  }

  @Override
  public int hashCode() {
    return Objects.hash(messageTemplateName, messageTemplateDescription, id, link);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetTemplates200ResponseMessagetemplatesInner {\n");
    sb.append("    messageTemplateName: ").append(toIndentedString(messageTemplateName)).append("\n");
    sb.append("    messageTemplateDescription: ").append(toIndentedString(messageTemplateDescription)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    link: ").append(toIndentedString(link)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("messageTemplateName");
    openapiFields.add("messageTemplateDescription");
    openapiFields.add("id");
    openapiFields.add("link");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to GetTemplates200ResponseMessagetemplatesInner
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (GetTemplates200ResponseMessagetemplatesInner.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in GetTemplates200ResponseMessagetemplatesInner is not found in the empty JSON string", GetTemplates200ResponseMessagetemplatesInner.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!GetTemplates200ResponseMessagetemplatesInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `GetTemplates200ResponseMessagetemplatesInner` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if (jsonObj.get("messageTemplateName") != null && !jsonObj.get("messageTemplateName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `messageTemplateName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("messageTemplateName").toString()));
      }
      if (jsonObj.get("messageTemplateDescription") != null && !jsonObj.get("messageTemplateDescription").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `messageTemplateDescription` to be a primitive type in the JSON string but got `%s`", jsonObj.get("messageTemplateDescription").toString()));
      }
      if (jsonObj.get("id") != null && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      JsonArray jsonArraylink = jsonObj.getAsJsonArray("link");
      if (jsonArraylink != null) {
        // ensure the json data is an array
        if (!jsonObj.get("link").isJsonArray()) {
          throw new IllegalArgumentException(String.format("Expected the field `link` to be an array in the JSON string but got `%s`", jsonObj.get("link").toString()));
        }

        // validate the optional field `link` (array)
        for (int i = 0; i < jsonArraylink.size(); i++) {
          LinkInner.validateJsonObject(jsonArraylink.get(i).getAsJsonObject());
        };
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetTemplates200ResponseMessagetemplatesInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetTemplates200ResponseMessagetemplatesInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetTemplates200ResponseMessagetemplatesInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetTemplates200ResponseMessagetemplatesInner.class));

       return (TypeAdapter<T>) new TypeAdapter<GetTemplates200ResponseMessagetemplatesInner>() {
           @Override
           public void write(JsonWriter out, GetTemplates200ResponseMessagetemplatesInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GetTemplates200ResponseMessagetemplatesInner read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of GetTemplates200ResponseMessagetemplatesInner given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of GetTemplates200ResponseMessagetemplatesInner
  * @throws IOException if the JSON string is invalid with respect to GetTemplates200ResponseMessagetemplatesInner
  */
  public static GetTemplates200ResponseMessagetemplatesInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetTemplates200ResponseMessagetemplatesInner.class);
  }

 /**
  * Convert an instance of GetTemplates200ResponseMessagetemplatesInner to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

