/*
 * Whispir Platform API
 * Whispir Platform API for cross channel and multi channel communications. Documentation on each endpoint is available at https://developers.whispir.com.
 *
 * The version of the OpenAPI document: 1.1.2
 * Contact: support@whispir.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import org.openapitools.client.model.LinkInner;
import org.openapitools.client.model.MessageStatusMessageStatusesInnerCategoriesInner;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import whispir_sdk_java.JSON;

/**
 * MessageStatusMessageStatusesInner
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-11-22T09:38:29.014059Z[Etc/UTC]")
public class MessageStatusMessageStatusesInner {
  public static final String SERIALIZED_NAME_LINK = "link";
  @SerializedName(SERIALIZED_NAME_LINK)
  private List<LinkInner> link = null;

  public static final String SERIALIZED_NAME_CATEGORIES = "categories";
  @SerializedName(SERIALIZED_NAME_CATEGORIES)
  private Set<MessageStatusMessageStatusesInnerCategoriesInner> categories = null;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_INFO = "info";
  @SerializedName(SERIALIZED_NAME_INFO)
  private String info;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private List<Object> status = null;

  public MessageStatusMessageStatusesInner() { 
  }

  
  public MessageStatusMessageStatusesInner(
     List<LinkInner> link
  ) {
    this();
    this.link = link;
  }

   /**
   * A [HATEOAS](https://en.wikipedia.org/wiki/HATEOAS) link object, describing all discoverable resources in relation to the original request.
   * @return link
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A [HATEOAS](https://en.wikipedia.org/wiki/HATEOAS) link object, describing all discoverable resources in relation to the original request.")

  public List<LinkInner> getLink() {
    return link;
  }




  public MessageStatusMessageStatusesInner categories(Set<MessageStatusMessageStatusesInnerCategoriesInner> categories) {
    
    this.categories = categories;
    return this;
  }

  public MessageStatusMessageStatusesInner addCategoriesItem(MessageStatusMessageStatusesInnerCategoriesInner categoriesItem) {
    if (this.categories == null) {
      this.categories = new LinkedHashSet<>();
    }
    this.categories.add(categoriesItem);
    return this;
  }

   /**
   * Present when &#x60;view&#x60; is &#x60;summary&#x60;.
   * @return categories
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Present when `view` is `summary`.")

  public Set<MessageStatusMessageStatusesInnerCategoriesInner> getCategories() {
    return categories;
  }


  public void setCategories(Set<MessageStatusMessageStatusesInnerCategoriesInner> categories) {
    this.categories = categories;
  }


  public MessageStatusMessageStatusesInner name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Present when &#x60;view&#x60; is &#x60;detailed&#x60;.
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "61400400400", value = "Present when `view` is `detailed`.")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public MessageStatusMessageStatusesInner info(String info) {
    
    this.info = info;
    return this;
  }

   /**
   * Present when &#x60;view&#x60; is &#x60;detailed&#x60;.
   * @return info
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "  SMS message sent. SMSCODE=008 SMS message received by device. SMSCODE=001 ", value = "Present when `view` is `detailed`.")

  public String getInfo() {
    return info;
  }


  public void setInfo(String info) {
    this.info = info;
  }


  public MessageStatusMessageStatusesInner status(List<Object> status) {
    
    this.status = status;
    return this;
  }

  public MessageStatusMessageStatusesInner addStatusItem(Object statusItem) {
    if (this.status == null) {
      this.status = new ArrayList<>();
    }
    this.status.add(statusItem);
    return this;
  }

   /**
   * Present when &#x60;view&#x60; is &#x60;detailed&#x60;.
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Present when `view` is `detailed`.")

  public List<Object> getStatus() {
    return status;
  }


  public void setStatus(List<Object> status) {
    this.status = status;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MessageStatusMessageStatusesInner messageStatusMessageStatusesInner = (MessageStatusMessageStatusesInner) o;
    return Objects.equals(this.link, messageStatusMessageStatusesInner.link) &&
        Objects.equals(this.categories, messageStatusMessageStatusesInner.categories) &&
        Objects.equals(this.name, messageStatusMessageStatusesInner.name) &&
        Objects.equals(this.info, messageStatusMessageStatusesInner.info) &&
        Objects.equals(this.status, messageStatusMessageStatusesInner.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(link, categories, name, info, status);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MessageStatusMessageStatusesInner {\n");
    sb.append("    link: ").append(toIndentedString(link)).append("\n");
    sb.append("    categories: ").append(toIndentedString(categories)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    info: ").append(toIndentedString(info)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("link");
    openapiFields.add("categories");
    openapiFields.add("name");
    openapiFields.add("info");
    openapiFields.add("status");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to MessageStatusMessageStatusesInner
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (MessageStatusMessageStatusesInner.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in MessageStatusMessageStatusesInner is not found in the empty JSON string", MessageStatusMessageStatusesInner.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!MessageStatusMessageStatusesInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `MessageStatusMessageStatusesInner` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      JsonArray jsonArraylink = jsonObj.getAsJsonArray("link");
      if (jsonArraylink != null) {
        // ensure the json data is an array
        if (!jsonObj.get("link").isJsonArray()) {
          throw new IllegalArgumentException(String.format("Expected the field `link` to be an array in the JSON string but got `%s`", jsonObj.get("link").toString()));
        }

        // validate the optional field `link` (array)
        for (int i = 0; i < jsonArraylink.size(); i++) {
          LinkInner.validateJsonObject(jsonArraylink.get(i).getAsJsonObject());
        };
      }
      JsonArray jsonArraycategories = jsonObj.getAsJsonArray("categories");
      if (jsonArraycategories != null) {
        // ensure the json data is an array
        if (!jsonObj.get("categories").isJsonArray()) {
          throw new IllegalArgumentException(String.format("Expected the field `categories` to be an array in the JSON string but got `%s`", jsonObj.get("categories").toString()));
        }

        // validate the optional field `categories` (array)
        for (int i = 0; i < jsonArraycategories.size(); i++) {
          MessageStatusMessageStatusesInnerCategoriesInner.validateJsonObject(jsonArraycategories.get(i).getAsJsonObject());
        };
      }
      if (jsonObj.get("name") != null && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if (jsonObj.get("info") != null && !jsonObj.get("info").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `info` to be a primitive type in the JSON string but got `%s`", jsonObj.get("info").toString()));
      }
      // ensure the json data is an array
      if (jsonObj.get("status") != null && !jsonObj.get("status").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `status` to be an array in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!MessageStatusMessageStatusesInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'MessageStatusMessageStatusesInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<MessageStatusMessageStatusesInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(MessageStatusMessageStatusesInner.class));

       return (TypeAdapter<T>) new TypeAdapter<MessageStatusMessageStatusesInner>() {
           @Override
           public void write(JsonWriter out, MessageStatusMessageStatusesInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public MessageStatusMessageStatusesInner read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of MessageStatusMessageStatusesInner given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of MessageStatusMessageStatusesInner
  * @throws IOException if the JSON string is invalid with respect to MessageStatusMessageStatusesInner
  */
  public static MessageStatusMessageStatusesInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, MessageStatusMessageStatusesInner.class);
  }

 /**
  * Convert an instance of MessageStatusMessageStatusesInner to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

