/*
 * Whispir Platform API
 * Whispir Platform API for cross channel and multi channel communications. Documentation on each endpoint is available at https://developers.whispir.com.
 *
 * The version of the OpenAPI document: 1.1.1
 * Contact: support@whispir.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.Attachment;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import whispir_sdk_java.JSON;

/**
 * Provides a configuration object for specifying custom audio for the voice header and body.
 */
@ApiModel(description = "Provides a configuration object for specifying custom audio for the voice header and body.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-11-22T09:15:03.121580Z[Etc/UTC]")
public class VoiceResources {
  public static final String SERIALIZED_NAME_ATTACHMENT = "attachment";
  @SerializedName(SERIALIZED_NAME_ATTACHMENT)
  private List<Attachment> attachment = null;

  public VoiceResources() { 
  }

  public VoiceResources attachment(List<Attachment> attachment) {
    
    this.attachment = attachment;
    return this;
  }

  public VoiceResources addAttachmentItem(Attachment attachmentItem) {
    if (this.attachment == null) {
      this.attachment = new ArrayList<>();
    }
    this.attachment.add(attachmentItem);
    return this;
  }

   /**
   * The header and body attachments containing WAV files. Read the following section for configuring each voice field attachment:  In addition to the parameters already specified for the TTS Voice calls, each attached WAV file must have the &#x60;attachmentDesc&#x60; named these specific values, to override the TTS voice:  | Voice field    | attachmentDesc | | -------------- |--------------- | | header         | &#x60;\&quot;voiceintro.wav\&quot;&#x60; | | body           | &#x60;\&quot;voicebody.wav\&quot;&#x60; |
   * @return attachment
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The header and body attachments containing WAV files. Read the following section for configuring each voice field attachment:  In addition to the parameters already specified for the TTS Voice calls, each attached WAV file must have the `attachmentDesc` named these specific values, to override the TTS voice:  | Voice field    | attachmentDesc | | -------------- |--------------- | | header         | `\"voiceintro.wav\"` | | body           | `\"voicebody.wav\"` |")

  public List<Attachment> getAttachment() {
    return attachment;
  }


  public void setAttachment(List<Attachment> attachment) {
    this.attachment = attachment;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VoiceResources voiceResources = (VoiceResources) o;
    return Objects.equals(this.attachment, voiceResources.attachment);
  }

  @Override
  public int hashCode() {
    return Objects.hash(attachment);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VoiceResources {\n");
    sb.append("    attachment: ").append(toIndentedString(attachment)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("attachment");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to VoiceResources
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (VoiceResources.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in VoiceResources is not found in the empty JSON string", VoiceResources.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!VoiceResources.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `VoiceResources` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      JsonArray jsonArrayattachment = jsonObj.getAsJsonArray("attachment");
      if (jsonArrayattachment != null) {
        // ensure the json data is an array
        if (!jsonObj.get("attachment").isJsonArray()) {
          throw new IllegalArgumentException(String.format("Expected the field `attachment` to be an array in the JSON string but got `%s`", jsonObj.get("attachment").toString()));
        }

        // validate the optional field `attachment` (array)
        for (int i = 0; i < jsonArrayattachment.size(); i++) {
          Attachment.validateJsonObject(jsonArrayattachment.get(i).getAsJsonObject());
        };
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!VoiceResources.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'VoiceResources' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<VoiceResources> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(VoiceResources.class));

       return (TypeAdapter<T>) new TypeAdapter<VoiceResources>() {
           @Override
           public void write(JsonWriter out, VoiceResources value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public VoiceResources read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of VoiceResources given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of VoiceResources
  * @throws IOException if the JSON string is invalid with respect to VoiceResources
  */
  public static VoiceResources fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, VoiceResources.class);
  }

 /**
  * Convert an instance of VoiceResources to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

